#region Copyright

// ©2002-2026 idéMobi
// www.idemobi.com

#endregion

namespace DMBSearchViewer
{
    /// <summary>
    ///     Configures DMBSearchViewer database locations and result limits.
    /// </summary>
    public sealed class DMBSearchViewerOptions
    {
        #region Instance fields and properties

        /// <summary>
        ///     Gets or sets the documentation database path generated by DMBDocumentationBuilder.
        /// </summary>
        public string DocumentationDatabasePath { get; set; } = "Documentation/data.db";

        /// <summary>
        ///     Gets or sets the maximum number of results requested from each provider.
        /// </summary>
        public int MaxResultsPerProvider { get; set; } = 20;

        /// <summary>
        ///     Gets or sets the search database path generated by DMBSearchBuilder.
        /// </summary>
        public string SearchBuilderDatabasePath { get; set; } = "Search/data.db";

        #endregion
    }
}