#region Copyright

// ©2002-2026 idéMobi
// www.idemobi.com

#endregion

#region

using DMBSearchCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Options;

#endregion

namespace DMBSearchViewer
{
    /// <summary>
    ///     Searches the SQLite database generated by DMBSearchBuilder.
    /// </summary>
    public sealed class SearchBuilderSearchProvider : ISearchProvider
    {
        #region Static methods

        private static bool HasWeightedTermIndex(SqliteConnection connection)
        {
            using SqliteCommand command = connection.CreateCommand();
            command.CommandText = """
                                  SELECT CASE
                                      WHEN EXISTS (SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'SearchPageTerms')
                                      THEN 1
                                      ELSE 0
                                  END;
                                  """;

            if (Convert.ToInt32(command.ExecuteScalar()) != 1)
            {
                return false;
            }

            using SqliteCommand countCommand = connection.CreateCommand();
            countCommand.CommandText = "SELECT EXISTS (SELECT 1 FROM SearchPageTerms LIMIT 1);";
            return Convert.ToInt32(countCommand.ExecuteScalar()) == 1;
        }

        private static string NormalizeResultUrl(string url)
        {
            if (Uri.TryCreate(url, UriKind.Absolute, out Uri? absoluteUri) &&
                (string.Equals(absoluteUri.Host, "localhost", StringComparison.OrdinalIgnoreCase) ||
                 string.Equals(absoluteUri.Host, "127.0.0.1", StringComparison.OrdinalIgnoreCase)))
            {
                return string.IsNullOrWhiteSpace(absoluteUri.PathAndQuery) ? "/" : absoluteUri.PathAndQuery;
            }

            return string.IsNullOrWhiteSpace(url) ? "/" : url;
        }

        #endregion

        #region Instance fields and properties

        private readonly IWebHostEnvironment _environment;
        private readonly SearchViewerOptions _options;

        #region From interface ISearchProvider

        /// <summary>
        ///     Gets the provider display name.
        /// </summary>
        public string Name => "DMBSearchBuilder";

        #endregion

        #endregion

        #region Instance constructors and destructors

        /// <summary>
        ///     Initializes a new instance of the <see cref="SearchBuilderSearchProvider" /> class.
        /// </summary>
        /// <param name="environment">The host environment used to resolve relative database paths.</param>
        /// <param name="options">The configured DMBSearchViewer options.</param>
        public SearchBuilderSearchProvider(IWebHostEnvironment environment, IOptions<SearchViewerOptions> options)
        {
            _environment = environment;
            _options = options.Value;
        }

        #endregion

        #region Instance methods

        private IReadOnlyList<SearchResult> ReadResults(SqliteCommand command, CancellationToken cancellationToken)
        {
            using SqliteDataReader reader = command.ExecuteReader();
            List<SearchResult> results = [];

            while (reader.Read())
            {
                cancellationToken.ThrowIfCancellationRequested();

                results.Add(new SearchResult
                {
                    SourceName = Name,
                    Title = reader["Title"]?.ToString() ?? string.Empty,
                    Url = NormalizeResultUrl(reader["Url"]?.ToString() ?? string.Empty),
                    Excerpt = reader["Description"]?.ToString() ?? string.Empty,
                    Score = Convert.ToDouble(reader["Score"])
                });
            }

            return results;
        }

        private IReadOnlyList<SearchResult> SearchLegacyIndex(
            SqliteConnection connection,
            SearchQuery query,
            IReadOnlyList<string> tokens,
            CancellationToken cancellationToken
        )
        {
            string tokenWhereClause = string.Join(
                " AND ",
                tokens.Select((_, index) => $"Keywords LIKE @Token{index}"));
            string compactQuery = SearchTextNormalizer.CompactSearchText(query.Term);

            using SqliteCommand command = connection.CreateCommand();
            command.CommandText = $"""
                                   SELECT Title, Url, Description,
                                          CASE
                                              WHEN Keywords LIKE @ExactQuery THEN 100
                                              WHEN REPLACE(Keywords, ' ', '') LIKE @CompactQuery THEN 85
                                              ELSE 60
                                          END AS Score
                                   FROM SearchPages
                                   WHERE ({tokenWhereClause})
                                      OR REPLACE(Keywords, ' ', '') LIKE @CompactQuery
                                   ORDER BY Score DESC, Title
                                   LIMIT @Limit;
                                   """;
            command.Parameters.AddWithValue("@ExactQuery", $"%{SearchTextNormalizer.NormalizeSearchText(query.Term)}%");
            command.Parameters.AddWithValue("@CompactQuery", $"%{compactQuery}%");
            command.Parameters.AddWithValue("@Limit", query.MaxResults);

            for (int index = 0; index < tokens.Count; index++)
            {
                command.Parameters.AddWithValue($"@Token{index}", $"%{tokens[index]}%");
            }

            return ReadResults(command, cancellationToken);
        }

        private IReadOnlyList<SearchResult> SearchWeightedIndex(
            SqliteConnection connection,
            SearchQuery query,
            IReadOnlyList<string> tokens,
            CancellationToken cancellationToken
        )
        {
            string tokenParameterList = string.Join(", ", tokens.Select((_, index) => $"@Token{index}"));
            string normalizedQuery = SearchTextNormalizer.NormalizeSearchText(query.Term);
            double phraseBonus = normalizedQuery.Contains(' ', StringComparison.Ordinal) ? 20.0 : 0.0;

            using SqliteCommand command = connection.CreateCommand();
            command.CommandText = $"""
                                   WITH Matches AS
                                   (
                                       SELECT PageId,
                                              SUM(Weight) AS WeightScore,
                                              COUNT(DISTINCT Term) AS MatchedTerms
                                       FROM SearchPageTerms
                                       WHERE Term IN ({tokenParameterList})
                                       GROUP BY PageId
                                       HAVING MatchedTerms = @TokenCount
                                   )
                                   SELECT SearchPages.Title,
                                          SearchPages.Url,
                                          SearchPages.Description,
                                          MIN(100.0, (Matches.WeightScore * 1.0 / @TokenCount) +
                                              CASE
                                                  WHEN @PhraseBonus > 0 AND SearchPages.Keywords LIKE @ExactQuery THEN @PhraseBonus
                                                  ELSE 0
                                              END) AS Score
                                   FROM Matches
                                   INNER JOIN SearchPages ON SearchPages.Id = Matches.PageId
                                   ORDER BY Score DESC, SearchPages.Title
                                   LIMIT @Limit;
                                   """;
            command.Parameters.AddWithValue("@TokenCount", tokens.Count);
            command.Parameters.AddWithValue("@ExactQuery", $"%{normalizedQuery}%");
            command.Parameters.AddWithValue("@PhraseBonus", phraseBonus);
            command.Parameters.AddWithValue("@Limit", query.MaxResults);

            for (int index = 0; index < tokens.Count; index++)
            {
                command.Parameters.AddWithValue($"@Token{index}", tokens[index]);
            }

            return ReadResults(command, cancellationToken);
        }

        #region From interface ISearchProvider

        /// <summary>
        ///     Searches the generated search database.
        /// </summary>
        /// <param name="query">The search query to execute.</param>
        /// <param name="cancellationToken">A token used to cancel the provider query.</param>
        /// <returns>A list of normalized search results.</returns>
        public Task<IReadOnlyList<SearchResult>> SearchAsync(SearchQuery query, CancellationToken cancellationToken)
        {
            string databasePath = SearchPathResolver.Resolve(_environment, _options.SearchBuilderDatabasePath);

            if (!File.Exists(databasePath) || string.IsNullOrWhiteSpace(query.Term))
            {
                return Task.FromResult<IReadOnlyList<SearchResult>>([]);
            }

            IReadOnlyList<string> tokens = SearchTextNormalizer.ExtractSearchTokens(query.Term);

            if (tokens.Count == 0)
            {
                return Task.FromResult<IReadOnlyList<SearchResult>>([]);
            }

            using SqliteConnection connection = new($"Data Source={databasePath}");
            connection.Open();

            if (HasWeightedTermIndex(connection))
            {
                IReadOnlyList<SearchResult> weightedResults = SearchWeightedIndex(connection, query, tokens, cancellationToken);

                if (weightedResults.Count > 0)
                {
                    return Task.FromResult(weightedResults);
                }
            }

            return Task.FromResult(SearchLegacyIndex(connection, query, tokens, cancellationToken));
        }

        #endregion

        #endregion
    }
}